version: "3"

services:
  hive-server:
    volumes:
      - ../docker_data/hdfs_data:/host_data
    hostname: hive-server.docker
  redis:
    image: redis:latest
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - ../docker_data/redis_data:/data
    hostname: redis.docker

  namenode:
    hostname: namenode.docker

  dns:
    hostname: dns.mageddo
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/resolv.conf:/etc/resolv.conf"
    image: defreitas/dns-proxy-server

volumes:
  redis: