version: "3"

services:
  hive-server:
    volumes:
      - ../docker_data/hdfs_data:/host_data
    hostname: hive-server.docker
    depends_on:
      - dns
  redis:
    depends_on:
      - dns
    image: redis:latest
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    volumes:
      - ../docker_data/redis_data:/data
    hostname: redis.docker

  cassandra:
    depends_on:
      - dns
    image: cassandra
    hostname: cassandra.docker
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    ports:
      - "9042:9042"

  namenode:
    hostname: namenode
    depends_on:
      - dns

  hive-metastore:
    hostname: hive-metastore.docker
    depends_on:
      - dns

  dns:
    hostname: dns.mageddo
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/resolv.conf:/etc/resolv.conf"
    image: defreitas/dns-proxy-server