version: "3"

services:
  hive-server:
    volumes:
      - ../docker_data/hdfs_data:/host_data
    hostname: hive-server

  cassandra:
    image: cassandra
    hostname: cassandra
    volumes:
      - ../docker_data/cassandra_data:/var/lib/cassandra
    ports:
      - "9042:9042"

  redis:
    image: redis:latest
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - ../docker_data/redis_data:/data
    hostname: redis

  namenode:
    hostname: namenode

  datanode:
    hostname: datanode

  dns:
    depends_on:
      - namenode
      - datanode
      - hive-server
      - redis
      - cassandra
    hostname: dns
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/resolv.conf:/etc/resolv.conf"
    image: defreitas/dns-proxy-server