[project]
name = "feast_sandbox"
version = "0.2.0"
description = ""
authors = [
    {name = "Felix Neko", email = "felix-neko@list.ru"}
]
requires-python = ">=3.9,<=3.12"
dependencies = [
    "feast[spark]==0.49.0",
    "protobuf<6",
    "pyspark<4",
]
